***Question No.1***

If you have a matrix A with dimensions (n, k) and a matrix B with dimensions (k, m), the resulting matrix C will have dimensions (n, m).So, for each element in the resulting matrix, you perform k multiplications and (k-1) additions.
So, for each element in the resulting matrix, you perform k multiplications and (k-1) additions. Since there are n * m elements in the resulting matrix, the total number of multiplications would be $ n*m*k $ and number of additions would be $n*m*(k-1)$

***Question No.2***

In [1]:
import numpy as np
import pandas as pd

In [2]:
M1 = [
    [1,2,3],
    [4,5,6]
]

In [3]:
M2 = [
    [7,8],
    [9,10],
    [11,12]
]

***MatriX Multipliction using List multiplication***

In [4]:
def matrix_mul_lists(A,B):
    result_matrix_list = [[0] * len(M2[0]) for _ in range(len(M1))]
    for i in range(len(M1)):
     for j in range(len(M2[0])):
         for k in range(len(M2)):
             result_matrix_list[i][j] += M1[i][k]*M2[k][j]
    return result_matrix_list

In [5]:
result_matrix_list = matrix_mul_lists(M1,M2)

In [6]:
result_matrix_list

[[58, 64], [139, 154]]

***Matrix Multilication using Numpy array***

In [7]:
M3 = np.array([[1,2,3],
              [4,5,6]])

In [8]:
M4 = np.array([[7,8],
               [9,10],
               [11,12]])

In [9]:
def matrix_mul_numpy(A,B):
    return M3@M4

In [10]:
result_Matrix_numpy = matrix_mul_numpy(M3,M4)

In [11]:
result_Matrix_numpy

array([[ 58,  64],
       [139, 154]])

In [12]:
import timeit
time_lists = timeit.timeit(lambda: matrix_mul_lists(M1, M2), number=10000)
time_numpy = timeit.timeit(lambda: matrix_mul_numpy(M3, M4), number=10000)

In [13]:
print(f"Time (list of lists): {time_lists:.6f} seconds")
print(f"Time (NumPy): {time_numpy:.6f} seconds")

Time (list of lists): 0.079715 seconds
Time (NumPy): 0.026067 seconds


***Question no.3***

This linear method of passes will take O(n) in each pass, so overall complexity will be O($n^2$). A better solution can be sorting the array and then simply returning the middle element. which will take O(nlogn) time.

In [14]:
list = [56,1,34,0,-1,88]

In [15]:
def median_linear_pass(arr):
    n = int(len(arr)/2)
    for i in range(n+1):
        maxi=0
        max=0
        for j in range(len(arr)-i):
            if arr[j]>max:
                max=arr[j]
                maxi=j
        arr[maxi]=arr[len(arr)-i-1]
        arr[len(arr)-i-1]=max
    return arr[n]

In [16]:
def median_sort(arr):
    sorted_arr = sorted(arr)
    n = len(sorted_arr)
    mid = n // 2
    if n % 2 == 1:
        return sorted_arr[mid]
    else:
        return (sorted_arr[mid - 1] + sorted_arr[mid]) / 2

In [17]:
import time
arr = np.random.rand(1000)

# Compare the time taken by each method with numpy's median routine
start_time = time.time()
linear_median = median_linear_pass(arr.copy())
linear_time = time.time() - start_time

start_time = time.time()
sort_median = median_sort(arr.copy())
sort_time = time.time() - start_time

start_time = time.time()
numpy_median = np.median(arr)
numpy_time = time.time() - start_time

print(f"Linear Method: Median = {linear_median}, Time = {linear_time} seconds")
print(f"Sorting Method: Median = {sort_median}, Time = {sort_time} seconds")
print(f"Numpy Median: Median = {numpy_median}, Time = {numpy_time} seconds")

Linear Method: Median = 0.5107772533216425, Time = 0.09712338447570801 seconds
Sorting Method: Median = 0.5103592063055823, Time = 0.0 seconds
Numpy Median: Median = 0.5103592063055823, Time = 0.010848045349121094 seconds


***Question No.4***

With Respect to x: 
    $2xy + y^3 cos(x) $  <br>
    
With Respect to y:
    $x^2 + 3y^2sin(x)$
    

***Question No.5***

In [18]:
!pip install jax jaxlib


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import jax
import jax.numpy as jnp

# Define the function x^2y + y^3 * sin(x)
def fun(x, y):
    return jnp.power(x, 2) * y + jnp.power(y, 3) * jnp.sin(x)

grad_fun = jax.grad(fun, argnums=(0, 1))
x_val = 2.0
y_val = 3.0
# Test the function with some values
der_x = grad_fun(x_val, y_val)[0]
der_y = grad_fun(x_val, y_val)[1]

print(f"Gradient with respect to x at x={x_val}, y={y_val}: {der_x}")
print(f"Gradient with respect to y at x={x_val}, y={y_val}: {der_y}")


Gradient with respect to x at x=2.0, y=3.0: 0.7640352249145508
Gradient with respect to y at x=2.0, y=3.0: 28.551029205322266


Analytical solution -
x = 2,y=3  
With Respect to x: 
    $=2*2*3 + 3^3 cos(2) $  <br>
    $=  12  +  27*cos(2)$ <br>
    $ = 0.76403541322 $ <br>
with respect to y:
    $= 2^2 + 3*3^2sin(2)$ <br>
    $= 4  +  27*sin(2)$<br>
    $= 28.5510305243
$

***Question No.6***

In [20]:
!pip install sympy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import sympy as sp

In [22]:
x,y=sp.symbols('x y')
exp = x**2 * y + y**3 * sp.sin(x)
der_x = sp.diff(exp,x)
der_y = sp.diff(exp,y)
print(der_x)
print(der_y)

2*x*y + y**3*cos(x)
x**2 + 3*y**2*sin(x)


***Question No.7***

In [23]:
pytn_dict={"2022":{"branch_1":{"Roll_No":101,"Name":'Harry',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":102,"Name":'Rohan',"Marks":{"Chemistry":90,"English":99}}},

       "2023":{"branch_1":{"Roll_No":201,"Name":'Krishna',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":202,"Name":'Hari',"Marks":{"Chemistry":85,"English":95}}},

       "2024":{"branch_1":{"Roll_No":301,"Name":'Mayank',"Marks":{"Physics":70,"Maths":28}},

              "branch_2":{"Roll_No":302,"Name":'Riyash',"Marks":{"Chemistry":92,"English":19}}},

       "2025":{"branch_1":{"Roll_No":401,"Name":'Ravi',"Marks":{"Physics":56,"Maths":48}},

              "branch_2":{"Roll_No":402,"Name":'Shivam',"Marks":{"Chemistry":60,"English":89}}}
       }

In [24]:
pytn_dict

{'2022': {'branch_1': {'Roll_No': 101,
   'Name': 'Harry',
   'Marks': {'Physics': 100, 'Maths': 98}},
  'branch_2': {'Roll_No': 102,
   'Name': 'Rohan',
   'Marks': {'Chemistry': 90, 'English': 99}}},
 '2023': {'branch_1': {'Roll_No': 201,
   'Name': 'Krishna',
   'Marks': {'Physics': 100, 'Maths': 98}},
  'branch_2': {'Roll_No': 202,
   'Name': 'Hari',
   'Marks': {'Chemistry': 85, 'English': 95}}},
 '2024': {'branch_1': {'Roll_No': 301,
   'Name': 'Mayank',
   'Marks': {'Physics': 70, 'Maths': 28}},
  'branch_2': {'Roll_No': 302,
   'Name': 'Riyash',
   'Marks': {'Chemistry': 92, 'English': 19}}},
 '2025': {'branch_1': {'Roll_No': 401,
   'Name': 'Ravi',
   'Marks': {'Physics': 56, 'Maths': 48}},
  'branch_2': {'Roll_No': 402,
   'Name': 'Shivam',
   'Marks': {'Chemistry': 60, 'English': 89}}}}

***Question No.8***

In [25]:
class Student:
    def __init__(self, year, branch, rollNo, name, **subjectWithMakrs):
        self.year=year
        self.branch=branch
        self.rollNo=rollNo
        self.name=name
        self.subjectWithMakrs=subjectWithMakrs

    def __str__(self):
        return f"Name: {self.name}, \nRoll No: {self.rollNo}, \nBranch: {self.branch}, \nYear: {self.year}, \nSubjects: {self.subjectWithMakrs}"


In [26]:
std1=Student(2022,"Computer Science",101,"sawan",Maths=100,Physics=98)
std2=Student(2023,"Computer Science",102,"prince",Maths=99,Physics=97)
print(std1.__str__())
print(std2.__str__())

Name: sawan, 
Roll No: 101, 
Branch: Computer Science, 
Year: 2022, 
Subjects: {'Maths': 100, 'Physics': 98}
Name: prince, 
Roll No: 102, 
Branch: Computer Science, 
Year: 2023, 
Subjects: {'Maths': 99, 'Physics': 97}


***Question no.10***

In [27]:
matrix=np.random.uniform(1.0,2.0,size=(20,5))
matrix

array([[1.71010343, 1.63355622, 1.77324142, 1.78485307, 1.54549293],
       [1.57232008, 1.2830136 , 1.00984058, 1.20228658, 1.49084798],
       [1.12370682, 1.30075453, 1.36034491, 1.25349911, 1.54172444],
       [1.13123682, 1.80296172, 1.71686274, 1.97621187, 1.84626007],
       [1.19224272, 1.88036369, 1.14617778, 1.11567956, 1.73641113],
       [1.36270956, 1.06812193, 1.69233599, 1.81596539, 1.00119813],
       [1.05147848, 1.79995603, 1.08298479, 1.24090396, 1.87791017],
       [1.13452263, 1.18211133, 1.02845555, 1.32839646, 1.88585732],
       [1.32367229, 1.32880961, 1.39744889, 1.24319129, 1.2315691 ],
       [1.17677513, 1.84920618, 1.62787164, 1.09159348, 1.8097945 ],
       [1.2308246 , 1.96756848, 1.13069518, 1.41317548, 1.95451674],
       [1.6254889 , 1.09076028, 1.45827853, 1.42091101, 1.98954127],
       [1.4204767 , 1.67502892, 1.67177115, 1.13669896, 1.3973653 ],
       [1.65802469, 1.63781434, 1.74964964, 1.44362385, 1.25566078],
       [1.70918244, 1.77337091, 1.

***Creating Dataframe from matrix***

In [28]:
df = pd.DataFrame(matrix, columns=['a','b','c','d','e'])
df

a         b         c         d         e
0   1.710103  1.633556  1.773241  1.784853  1.545493
1   1.572320  1.283014  1.009841  1.202287  1.490848
2   1.123707  1.300755  1.360345  1.253499  1.541724
3   1.131237  1.802962  1.716863  1.976212  1.846260
4   1.192243  1.880364  1.146178  1.115680  1.736411
5   1.362710  1.068122  1.692336  1.815965  1.001198
6   1.051478  1.799956  1.082985  1.240904  1.877910
7   1.134523  1.182111  1.028456  1.328396  1.885857
8   1.323672  1.328810  1.397449  1.243191  1.231569
9   1.176775  1.849206  1.627872  1.091593  1.809795
10  1.230825  1.967568  1.130695  1.413175  1.954517
11  1.625489  1.090760  1.458279  1.420911  1.989541
12  1.420477  1.675029  1.671771  1.136699  1.397365
13  1.658025  1.637814  1.749650  1.443624  1.255661
14  1.709182  1.773371  1.971079  1.092457  1.752789
15  1.566541  1.858301  1.465393  1.719018  1.345372
16  1.647196  1.529888  1.541130  1.769511  1.040357
17  1.200929  1.142459  1.201833  1.813740  1.661197
18  1.557669  1.521658  1.036951  1.754472  1.515029
19  1.330775  1.395565  1.164434  1.475716  1.266348

**Column with highest S.D**

In [29]:
std_deviation = np.std(matrix, axis=0)
print(std_deviation)
max_SD_column = np.argmax(std_deviation)
df.columns[max_SD_column]

[0.21943164 0.28485154 0.28984693 0.28216825 0.29317183]


'e'

***Row with the lowest mean***

In [30]:
means = np.mean(matrix, axis=1)
row = np.argmin(means)
print(f'Row no.: {row}')
for i in df.columns:
    print(f'\t\t\t{i}',end='')
print()
for i in df.columns:
    print(f'\t{df[i][row]}',end='')

Row no.: 8
			a			b			c			d			e
	1.3236722891895707	1.3288096116390995	1.397448889190272	1.2431912855079166	1.2315691024887896

***Question No.11***

In [31]:
#Add a new Column
for index, row in df.iterrows():
    df.loc[index, 'f'] = sum(row)

In [32]:
df

a         b         c         d         e         f
0   1.710103  1.633556  1.773241  1.784853  1.545493  8.447247
1   1.572320  1.283014  1.009841  1.202287  1.490848  6.558309
2   1.123707  1.300755  1.360345  1.253499  1.541724  6.580030
3   1.131237  1.802962  1.716863  1.976212  1.846260  8.473533
4   1.192243  1.880364  1.146178  1.115680  1.736411  7.070875
5   1.362710  1.068122  1.692336  1.815965  1.001198  6.940331
6   1.051478  1.799956  1.082985  1.240904  1.877910  7.053233
7   1.134523  1.182111  1.028456  1.328396  1.885857  6.559343
8   1.323672  1.328810  1.397449  1.243191  1.231569  6.524691
9   1.176775  1.849206  1.627872  1.091593  1.809795  7.555241
10  1.230825  1.967568  1.130695  1.413175  1.954517  7.696780
11  1.625489  1.090760  1.458279  1.420911  1.989541  7.584980
12  1.420477  1.675029  1.671771  1.136699  1.397365  7.301341
13  1.658025  1.637814  1.749650  1.443624  1.255661  7.744773
14  1.709182  1.773371  1.971079  1.092457  1.752789  8.298879
15  1.566541  1.858301  1.465393  1.719018  1.345372  7.954625
16  1.647196  1.529888  1.541130  1.769511  1.040357  7.528081
17  1.200929  1.142459  1.201833  1.813740  1.661197  7.020159
18  1.557669  1.521658  1.036951  1.754472  1.515029  7.385780
19  1.330775  1.395565  1.164434  1.475716  1.266348  6.632837

In [33]:
#Adding column g
for index, row in df.iterrows():
    df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'

C:\Users\hp\AppData\Local\Temp\ipykernel_11340\2910906865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'
C:\Users\hp\AppData\Local\Temp\ipykernel_11340\2910906865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'


In [34]:
df

a         b         c         d         e         f    g
0   1.710103  1.633556  1.773241  1.784853  1.545493  8.447247  GT8
1   1.572320  1.283014  1.009841  1.202287  1.490848  6.558309  LT8
2   1.123707  1.300755  1.360345  1.253499  1.541724  6.580030  LT8
3   1.131237  1.802962  1.716863  1.976212  1.846260  8.473533  GT8
4   1.192243  1.880364  1.146178  1.115680  1.736411  7.070875  LT8
5   1.362710  1.068122  1.692336  1.815965  1.001198  6.940331  LT8
6   1.051478  1.799956  1.082985  1.240904  1.877910  7.053233  LT8
7   1.134523  1.182111  1.028456  1.328396  1.885857  6.559343  LT8
8   1.323672  1.328810  1.397449  1.243191  1.231569  6.524691  LT8
9   1.176775  1.849206  1.627872  1.091593  1.809795  7.555241  LT8
10  1.230825  1.967568  1.130695  1.413175  1.954517  7.696780  LT8
11  1.625489  1.090760  1.458279  1.420911  1.989541  7.584980  LT8
12  1.420477  1.675029  1.671771  1.136699  1.397365  7.301341  LT8
13  1.658025  1.637814  1.749650  1.443624  1.255661  7.744773  LT8
14  1.709182  1.773371  1.971079  1.092457  1.752789  8.298879  GT8
15  1.566541  1.858301  1.465393  1.719018  1.345372  7.954625  LT8
16  1.647196  1.529888  1.541130  1.769511  1.040357  7.528081  LT8
17  1.200929  1.142459  1.201833  1.813740  1.661197  7.020159  LT8
18  1.557669  1.521658  1.036951  1.754472  1.515029  7.385780  LT8
19  1.330775  1.395565  1.164434  1.475716  1.266348  6.632837  LT8

In [35]:
#Finding No. of rows in the dataframe where the value in the column “g” is “LT8
df['g'].value_counts()

g
LT8    17
GT8     3
Name: count, dtype: int64

In [36]:
#finding std deviation of f where g == 'GT8' and g == 'LT8'
std_dev_LT8 = df[df['g'] == 'LT8']['f'].std()

# Standard deviation of 'f' where 'g' is 'GT8'
std_dev_GT8 = df[df['g'] == 'GT8']['f'].std()

print(f"Std dev of 'f' where 'g' is 'LT8': {std_dev_LT8}")
print(f"Std dev of 'f' where 'g' is 'GT8': {std_dev_GT8}")

Std dev of 'f' where 'g' is 'LT8': 0.4764839108361239
Std dev of 'f' where 'g' is 'GT8': 0.09417040757328662


***Question No.12***

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Perform broadcasting operation (element-wise addition)
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


***Question NO. 13***

In [38]:
arr= np.random.randint(1,100,100)
def custom_argmin(arr):
    min_value = arr[0]
    min_index = 0
    for i in range(1, len(arr)):
        if arr[i] < min_value:
            min_value = arr[i]
            min_index = i

    return min_index

custom_argminimum = custom_argmin(arr)

print("Custom argmin:", custom_argminimum)
print("NumPy argmin:", np.argmin(arr))

Custom argmin: 50
NumPy argmin: 50
