***Question No.1***

If you have a matrix A with dimensions (n, k) and a matrix B with dimensions (k, m), the resulting matrix C will have dimensions (n, m).So, for each element in the resulting matrix, you perform k multiplications and (k-1) additions.
So, for each element in the resulting matrix, you perform k multiplications and (k-1) additions. Since there are n * m elements in the resulting matrix, the total number of multiplications would be $ n*m*k $ and number of additions would be $n*m*(k-1)$

***Question No.2***

In [1]:
import numpy as np
import pandas as pd

In [2]:
M1 = [
    [1,2,3],
    [4,5,6]
]

In [3]:
M2 = [
    [7,8],
    [9,10],
    [11,12]
]

***MatriX Multipliction using List multiplication***

In [4]:
def matrix_mul_lists(A,B):
    result_matrix_list = [[0] * len(M2[0]) for _ in range(len(M1))]
    for i in range(len(M1)):
     for j in range(len(M2[0])):
         for k in range(len(M2)):
             result_matrix_list[i][j] += M1[i][k]*M2[k][j]
    return result_matrix_list

In [5]:
result_matrix_list = matrix_mul_lists(M1,M2)

In [6]:
result_matrix_list

[[58, 64], [139, 154]]

***Matrix Multilication using Numpy array***

In [7]:
M3 = np.array([[1,2,3],
              [4,5,6]])

In [8]:
M4 = np.array([[7,8],
               [9,10],
               [11,12]])

In [9]:
def matrix_mul_numpy(A,B):
    return M3@M4

In [10]:
result_Matrix_numpy = matrix_mul_numpy(M3,M4)

In [11]:
result_Matrix_numpy

array([[ 58,  64],
       [139, 154]])

In [12]:
import timeit
time_lists = timeit.timeit(lambda: matrix_mul_lists(M1, M2), number=10000)
time_numpy = timeit.timeit(lambda: matrix_mul_numpy(M3, M4), number=10000)

In [13]:
print(f"Time (list of lists): {time_lists:.6f} seconds")
print(f"Time (NumPy): {time_numpy:.6f} seconds")

Time (list of lists): 0.085237 seconds
Time (NumPy): 0.022936 seconds


***Question no.3***

This linear method of passes will take O(n) in each pass, so overall complexity will be O($n^2$). A better solution can be sorting the array and then simply returning the middle element. which will take O(nlogn) time.

In [14]:
list = [56,1,34,0,-1,88]

In [15]:
def median_linear_pass(arr):
    n = int(len(arr)/2)
    for i in range(n+1):
        maxi=0
        max=0
        for j in range(len(arr)-i):
            if arr[j]>max:
                max=arr[j]
                maxi=j
        arr[maxi]=arr[len(arr)-i-1]
        arr[len(arr)-i-1]=max
    return arr[n]

In [16]:
def median_sort(arr):
    sorted_arr = sorted(arr)
    n = len(sorted_arr)
    mid = n // 2
    if n % 2 == 1:
        return sorted_arr[mid]
    else:
        return (sorted_arr[mid - 1] + sorted_arr[mid]) / 2

In [17]:
import time
arr = np.random.rand(1000)

# Compare the time taken by each method with numpy's median routine
start_time = time.time()
linear_median = median_linear_pass(arr.copy())
linear_time = time.time() - start_time

start_time = time.time()
sort_median = median_sort(arr.copy())
sort_time = time.time() - start_time

start_time = time.time()
numpy_median = np.median(arr)
numpy_time = time.time() - start_time

print(f"Linear Method: Median = {linear_median}, Time = {linear_time} seconds")
print(f"Sorting Method: Median = {sort_median}, Time = {sort_time} seconds")
print(f"Numpy Median: Median = {numpy_median}, Time = {numpy_time} seconds")

Linear Method: Median = 0.4982258443181843, Time = 0.08709931373596191 seconds
Sorting Method: Median = 0.4979055133399061, Time = 0.015968799591064453 seconds
Numpy Median: Median = 0.4979055133399061, Time = 0.0 seconds


***Question No.4***

With Respect to x: 
    $2xy + y^3 cos(x) $  <br>
    
With Respect to y:
    $x^2 + 3y^2sin(x)$
    

***Question No.5***

In [18]:
!pip install jax jaxlib


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import jax
import jax.numpy as jnp

# Define the function x^2y + y^3 * sin(x)
def fun(x, y):
    return jnp.power(x, 2) * y + jnp.power(y, 3) * jnp.sin(x)

grad_fun = jax.grad(fun, argnums=(0, 1))
x_val = 2.0
y_val = 3.0
# Test the function with some values
der_x = grad_fun(x_val, y_val)[0]
der_y = grad_fun(x_val, y_val)[1]

print(f"Gradient with respect to x at x={x_val}, y={y_val}: {der_x}")
print(f"Gradient with respect to y at x={x_val}, y={y_val}: {der_y}")


Gradient with respect to x at x=2.0, y=3.0: 0.7640352249145508
Gradient with respect to y at x=2.0, y=3.0: 28.551029205322266


Analytical solution -
x = 2,y=3  
With Respect to x: 
    $=2*2*3 + 3^3 cos(2) $  <br>
    $=  12  +  27*cos(2)$ <br>
    $ = 0.76403541322 $ <br>
with respect to y:
    $= 2^2 + 3*3^2sin(2)$ <br>
    $= 4  +  27*sin(2)$<br>
    $= 28.5510305243
$

***Question No.6***

In [20]:
!pip install sympy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import sympy as sp

In [22]:
x,y=sp.symbols('x y')
exp = x**2 * y + y**3 * sp.sin(x)
der_x = sp.diff(exp,x)
der_y = sp.diff(exp,y)
print(der_x)
print(der_y)

2*x*y + y**3*cos(x)
x**2 + 3*y**2*sin(x)


***Question No.7***

In [23]:
pytn_dict={"2022":{"branch_1":{"Roll_No":101,"Name":'Harry',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":102,"Name":'Rohan',"Marks":{"Chemistry":90,"English":99}}},

       "2023":{"branch_1":{"Roll_No":201,"Name":'Krishna',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":202,"Name":'Hari',"Marks":{"Chemistry":85,"English":95}}},

       "2024":{"branch_1":{"Roll_No":301,"Name":'Mayank',"Marks":{"Physics":70,"Maths":28}},

              "branch_2":{"Roll_No":302,"Name":'Riyash',"Marks":{"Chemistry":92,"English":19}}},

       "2025":{"branch_1":{"Roll_No":401,"Name":'Ravi',"Marks":{"Physics":56,"Maths":48}},

              "branch_2":{"Roll_No":402,"Name":'Shivam',"Marks":{"Chemistry":60,"English":89}}}
       }

In [24]:
pytn_dict

{'2022': {'branch_1': {'Roll_No': 101,
   'Name': 'Harry',
   'Marks': {'Physics': 100, 'Maths': 98}},
  'branch_2': {'Roll_No': 102,
   'Name': 'Rohan',
   'Marks': {'Chemistry': 90, 'English': 99}}},
 '2023': {'branch_1': {'Roll_No': 201,
   'Name': 'Krishna',
   'Marks': {'Physics': 100, 'Maths': 98}},
  'branch_2': {'Roll_No': 202,
   'Name': 'Hari',
   'Marks': {'Chemistry': 85, 'English': 95}}},
 '2024': {'branch_1': {'Roll_No': 301,
   'Name': 'Mayank',
   'Marks': {'Physics': 70, 'Maths': 28}},
  'branch_2': {'Roll_No': 302,
   'Name': 'Riyash',
   'Marks': {'Chemistry': 92, 'English': 19}}},
 '2025': {'branch_1': {'Roll_No': 401,
   'Name': 'Ravi',
   'Marks': {'Physics': 56, 'Maths': 48}},
  'branch_2': {'Roll_No': 402,
   'Name': 'Shivam',
   'Marks': {'Chemistry': 60, 'English': 89}}}}

***Question No.8***

In [25]:
class Student:
    def __init__(self, year, branch, rollNo, name, **subjectWithMakrs):
        self.year=year
        self.branch=branch
        self.rollNo=rollNo
        self.name=name
        self.subjectWithMakrs=subjectWithMakrs

    def __str__(self):
        return f"Name: {self.name}, \nRoll No: {self.rollNo}, \nBranch: {self.branch}, \nYear: {self.year}, \nSubjects: {self.subjectWithMakrs}"


In [26]:
std1=Student(2022,"Computer Science",101,"sawan",Maths=100,Physics=98)
std2=Student(2023,"Computer Science",102,"prince",Maths=99,Physics=97)
print(std1.__str__())
print(std2.__str__())

Name: sawan, 
Roll No: 101, 
Branch: Computer Science, 
Year: 2022, 
Subjects: {'Maths': 100, 'Physics': 98}
Name: prince, 
Roll No: 102, 
Branch: Computer Science, 
Year: 2023, 
Subjects: {'Maths': 99, 'Physics': 97}


***Question no.10***

In [27]:
matrix=np.random.uniform(1.0,2.0,size=(20,5))
matrix

array([[1.42713889, 1.79037267, 1.95987106, 1.93169131, 1.92980177],
       [1.70581039, 1.03781864, 1.68880325, 1.85950198, 1.10864695],
       [1.54311435, 1.31238931, 1.50245268, 1.52205738, 1.93913055],
       [1.4971826 , 1.77629103, 1.37595307, 1.65473742, 1.8207601 ],
       [1.4868385 , 1.03919166, 1.16695416, 1.13574905, 1.06722503],
       [1.15530985, 1.91120625, 1.45984416, 1.56281926, 1.12323193],
       [1.87162214, 1.80400342, 1.27955266, 1.93704027, 1.71617891],
       [1.72534809, 1.45900114, 1.53490366, 1.29829735, 1.04394894],
       [1.95966866, 1.17509697, 1.2938227 , 1.71253378, 1.38345478],
       [1.17555113, 1.31900519, 1.68713563, 1.57793283, 1.58517713],
       [1.70666198, 1.49576057, 1.36544598, 1.22783442, 1.76278583],
       [1.4907775 , 1.04189075, 1.81522918, 1.49111631, 1.2480892 ],
       [1.02112136, 1.68397665, 1.15309329, 1.95712119, 1.26320955],
       [1.95291155, 1.05621048, 1.97855062, 1.24623031, 1.30617152],
       [1.04988296, 1.94864529, 1.

***Creating Dataframe from matrix***

In [28]:
df = pd.DataFrame(matrix, columns=['a','b','c','d','e'])
df

a         b         c         d         e
0   1.427139  1.790373  1.959871  1.931691  1.929802
1   1.705810  1.037819  1.688803  1.859502  1.108647
2   1.543114  1.312389  1.502453  1.522057  1.939131
3   1.497183  1.776291  1.375953  1.654737  1.820760
4   1.486839  1.039192  1.166954  1.135749  1.067225
5   1.155310  1.911206  1.459844  1.562819  1.123232
6   1.871622  1.804003  1.279553  1.937040  1.716179
7   1.725348  1.459001  1.534904  1.298297  1.043949
8   1.959669  1.175097  1.293823  1.712534  1.383455
9   1.175551  1.319005  1.687136  1.577933  1.585177
10  1.706662  1.495761  1.365446  1.227834  1.762786
11  1.490778  1.041891  1.815229  1.491116  1.248089
12  1.021121  1.683977  1.153093  1.957121  1.263210
13  1.952912  1.056210  1.978551  1.246230  1.306172
14  1.049883  1.948645  1.989791  1.442166  1.336186
15  1.251481  1.597690  1.463385  1.273782  1.541398
16  1.902105  1.196110  1.613260  1.017344  1.226054
17  1.408799  1.751404  1.261596  1.728470  1.924050
18  1.024040  1.127761  1.062000  1.166743  1.647403
19  1.610315  1.223693  1.736396  1.883112  1.837820

**Column with highest S.D**

In [29]:
std_deviation = np.std(matrix, axis=0)
print(std_deviation)
max_SD_column = np.argmax(std_deviation)
df.columns[max_SD_column]

[0.30201278 0.31359586 0.27571058 0.29025824 0.30676037]


'b'

***Row with the lowest mean***

In [30]:
means = np.mean(matrix, axis=1)
row = np.argmin(means)
print(f'Row no.: {row}')
for i in df.columns:
    print(f'\t\t\t{i}',end='')
print()
for i in df.columns:
    print(f'\t{df[i][row]}',end='')

Row no.: 4
			a			b			c			d			e
	1.4868385033947105	1.0391916649141626	1.1669541573018152	1.135749054599466	1.067225030490148

***Question No.11***

In [31]:
#Add a new Column
for index, row in df.iterrows():
    df.loc[index, 'f'] = sum(row)

In [32]:
df

a         b         c         d         e         f
0   1.427139  1.790373  1.959871  1.931691  1.929802  9.038876
1   1.705810  1.037819  1.688803  1.859502  1.108647  7.400581
2   1.543114  1.312389  1.502453  1.522057  1.939131  7.819144
3   1.497183  1.776291  1.375953  1.654737  1.820760  8.124924
4   1.486839  1.039192  1.166954  1.135749  1.067225  5.895958
5   1.155310  1.911206  1.459844  1.562819  1.123232  7.212411
6   1.871622  1.804003  1.279553  1.937040  1.716179  8.608397
7   1.725348  1.459001  1.534904  1.298297  1.043949  7.061499
8   1.959669  1.175097  1.293823  1.712534  1.383455  7.524577
9   1.175551  1.319005  1.687136  1.577933  1.585177  7.344802
10  1.706662  1.495761  1.365446  1.227834  1.762786  7.558489
11  1.490778  1.041891  1.815229  1.491116  1.248089  7.087103
12  1.021121  1.683977  1.153093  1.957121  1.263210  7.078522
13  1.952912  1.056210  1.978551  1.246230  1.306172  7.540074
14  1.049883  1.948645  1.989791  1.442166  1.336186  7.766671
15  1.251481  1.597690  1.463385  1.273782  1.541398  7.127735
16  1.902105  1.196110  1.613260  1.017344  1.226054  6.954872
17  1.408799  1.751404  1.261596  1.728470  1.924050  8.074319
18  1.024040  1.127761  1.062000  1.166743  1.647403  6.027948
19  1.610315  1.223693  1.736396  1.883112  1.837820  8.291337

In [33]:
#Adding column g
for index, row in df.iterrows():
    df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'

C:\Users\hp\AppData\Local\Temp\ipykernel_13220\2910906865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'
C:\Users\hp\AppData\Local\Temp\ipykernel_13220\2910906865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[index, 'g'] = 'LT8' if row[5]<8 else 'GT8'


In [34]:
df

a         b         c         d         e         f    g
0   1.427139  1.790373  1.959871  1.931691  1.929802  9.038876  GT8
1   1.705810  1.037819  1.688803  1.859502  1.108647  7.400581  LT8
2   1.543114  1.312389  1.502453  1.522057  1.939131  7.819144  LT8
3   1.497183  1.776291  1.375953  1.654737  1.820760  8.124924  GT8
4   1.486839  1.039192  1.166954  1.135749  1.067225  5.895958  LT8
5   1.155310  1.911206  1.459844  1.562819  1.123232  7.212411  LT8
6   1.871622  1.804003  1.279553  1.937040  1.716179  8.608397  GT8
7   1.725348  1.459001  1.534904  1.298297  1.043949  7.061499  LT8
8   1.959669  1.175097  1.293823  1.712534  1.383455  7.524577  LT8
9   1.175551  1.319005  1.687136  1.577933  1.585177  7.344802  LT8
10  1.706662  1.495761  1.365446  1.227834  1.762786  7.558489  LT8
11  1.490778  1.041891  1.815229  1.491116  1.248089  7.087103  LT8
12  1.021121  1.683977  1.153093  1.957121  1.263210  7.078522  LT8
13  1.952912  1.056210  1.978551  1.246230  1.306172  7.540074  LT8
14  1.049883  1.948645  1.989791  1.442166  1.336186  7.766671  LT8
15  1.251481  1.597690  1.463385  1.273782  1.541398  7.127735  LT8
16  1.902105  1.196110  1.613260  1.017344  1.226054  6.954872  LT8
17  1.408799  1.751404  1.261596  1.728470  1.924050  8.074319  GT8
18  1.024040  1.127761  1.062000  1.166743  1.647403  6.027948  LT8
19  1.610315  1.223693  1.736396  1.883112  1.837820  8.291337  GT8

In [35]:
#Finding No. of rows in the dataframe where the value in the column “g” is “LT8
df['g'].value_counts()

g
LT8    15
GT8     5
Name: count, dtype: int64

In [36]:
#finding std deviation of f where g == 'GT8' and g == 'LT8'
std_dev_LT8 = df[df['g'] == 'LT8']['f'].std()

# Standard deviation of 'f' where 'g' is 'GT8'
std_dev_GT8 = df[df['g'] == 'GT8']['f'].std()

print(f"Std dev of 'f' where 'g' is 'LT8': {std_dev_LT8}")
print(f"Std dev of 'f' where 'g' is 'GT8': {std_dev_GT8}")

Std dev of 'f' where 'g' is 'LT8': 0.5527581868913516
Std dev of 'f' where 'g' is 'GT8': 0.40041639688762887


***Question No.12***

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Perform broadcasting operation (element-wise addition)
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]
